# Generated by Django 6.0.5 on 2026-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='service_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='service_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('Oil Change', 'Oil Change'), ('Brake Service', 'Brake Service'), ('General Service', 'General Service'), ('Battery Check', 'Battery Check'), ('Wheel Alignment', 'Wheel Alignment')], max_length=50),
        ),
    ]
