# Generated by Django 6.0.7 on 2026-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointment_date_appointment_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dropoff_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pickup_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='request_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='request_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('Oil Change', 'Oil Change'), ('Brake Service', 'Brake Service'), ('General Service', 'General Service'), ('Battery Check', 'Battery Check'), ('Wheel Alignment', 'Wheel Alignment'), ('Water Service', 'Water Service'), ('Other', 'Other')], max_length=50),
        ),
    ]
