# Generated by Django 5.2 on 2026-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='home_service_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='home_service_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='request_home_service',
            field=models.BooleanField(default=False),
        ),
    ]
