# Generated by Django 5.2 on 2026-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_home_service_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('Basic Service', 'Basic Service'), ('Standard Service', 'Standard Service'), ('Comprehensive Service', 'Comprehensive Service'), ('Running Repair', 'Running Repair'), ('Jump Start', 'Jump Start'), ('Puncture', 'Puncture'), ('Other', 'Other')], max_length=50),
        ),
    ]
