# Generated by Django 6.0.5 on 2026-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
